// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Article is the predicate function for article builders.
type Article func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)
